var levels=[
    {
        level:1,
        coinsInfo:[Coin.GoldCoin],
        winScore:100
    },
    {
        level:2,
        coinsInfo:[Coin.GoldCoin,Coin.OrangeCoin],
        winScore:200
    },
    {
        level:3,
        coinsInfo:[Coin.GoldCoin,Coin.OrangeCoin,Coin.PurpleCoin],
        winScore:250
    },
    {
        level:4,
        coinsInfo:[Coin.GoldCoin,Coin.RedCoin,Coin.PurpleCoin],
        winScore:300
    },
    {
        level:5,
        coinsInfo:[Coin.OrangeCoin,Coin.RedCoin,Coin.PurpleCoin,Coin.GreenCoin],
        winScore:350
    },
    {
        level:6,
        coinsInfo:[Coin.GoldCoin,Coin.OrangeCoin,Coin.RedCoin,
            Coin.PurpleCoin,Coin.GreenCoin,Coin.BlackCoin],
        winScore:400
    }
];